### ISSUE TITLE
Devtools crashes when opening a Connect component

### ISSUE THREAD

**Issue by AngeloYoun** [metal/metal-devtools#15]
There is something in my store which is causing the devtools to repeatedly print out

```
Args: 
VM1032:642  metal-devtools extension: (`clone`)

    TypeError: Illegal constructor

    at cloneObj (<anonymous>:639:20)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
    at cloneObj (<anonymous>:649:26)
```
Until chrome crashes. TT ^ TT

It may have something to do with some dom elements I have in the store.

**Comment by mthadley** [comment]
So I'm guessing there are probably two different problems here working together. 

The first is trying to clone DOM elements. If you try something like this in your console, you should see the same `TypeError`:
```js
var Constructor = document.constructor;
new Constructor();
```
We could probably handle this case better. Maybe we could move the `try/catch` to just around the `default` case. If it fails, we can instead just send over the `constructor.name`. That way instead of not including the prop, the developer instead sees something like `myProp: HtmlDocument`.

The second issue is that we are probably trying to clone an object whose references form a cycle. So something like this:
```js
var x = {doc: document};
var y = {doc: document};
x.ref = y;
y.ref = x;
```
This should at least be pretty easy to fix.

**Comment by bryceosterhaus** [comment]
Fixed by https://github.com/metal/metal-devtools/pull/16 & https://github.com/metal/metal-devtools/commit/2bf95d62de655c0d22cc25bd4a69485289a2c9db
