### ISSUE TITLE
When a component renders, this.props.children, the component pane doesn't show state/prop details

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-devtools#25]
We're using an InfiniteScroll component, that has childComponents. 
`<InfiniteScroll>`
`<List data={data} />`
`</InfiniteScroll>`

Within InfiniteScroll, we have this rendering the children.
`	render() {`
	`	return <div>{this.props.children}</div>;`
`}`

but the component pane doesn't show any of the child component details.

**Comment by bryceosterhaus** [comment]
Hey @ssmith353, currently we blacklist `props.children` from the state pane. Initial reason was because of a technical challenge(although I don't know if thats an issue any more) and also because those child objects can contain a lot of information that might be heavy on the state pane(especially dom references).

As I look into it more though, what information would be helpful to you when inspecting those props?

In the mean time, are you able to gain the info you need about the children via the component tree?

**Comment by bryceosterhaus** [comment]
Just updated master to include showing children in the state pane. Its a little wonky right now, but if you want you can clone the repo and give it a try. Let me know what you think

**Comment by ssmith353** [comment]
Hey thanks @bryceosterhaus! I'll check that out and get back to you!

**Comment by ssmith353** [comment]
hey @bryceosterhaus, We actually removed this component before I got a chance to test the latest master. :/ 

Thanks for taking the time to look into it though!
